### PR TITLE
Merge rust-vmm/kvm-ioctls changes into this fork

### PR DESCRIPTION
**Pull request by dianpopa**
*Description of changes:*
 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sandreim — COMMENTED** [review]
Please bump kvm-bindings version and update it in Cargo.toml here.

`kvm-bindings = { git = "https://github.com/firecracker-microvm/kvm-bindings", tag = "v0.2.0-2", features = ["fam-wrappers"] }`

**Review by acatangiu — APPROVED** [review]

**Comment by acatangiu** [comment]
> Please bump kvm-bindings version and update it in Cargo.toml here.
> 
> `kvm-bindings = { git = "https://github.com/firecracker-microvm/kvm-bindings", tag = "v0.2.0-2", features = ["fam-wrappers"] }`

I propose to keep this PR as is - clean upstream merge - and bump dependencies in a subsequent PR.

Historically deps have been bumped in the _new version release PR_ so you could do the same now.

**Comment by sandreim** [comment]
> > Please bump kvm-bindings version and update it in Cargo.toml here.
> > `kvm-bindings = { git = "https://github.com/firecracker-microvm/kvm-bindings", tag = "v0.2.0-2", features = ["fam-wrappers"] }`
> 
> I propose to keep this PR as is - clean upstream merge - and bump dependencies in a subsequent PR.
> 
> Historically deps have been bumped in the _new version release PR_ so you could do the same now.

I can agree to this.  I was thinking it makes sense to have it in a single PR to avoid the overhead of creating and reviewing 2 of them.

**Review by sandreim — APPROVED** [review]

**Comment by dianpopa** [comment]
Closing in favor of #7.

**Pull request closed without merging**
